language: node_js
node_js:
- '0.10'
before_script:
- npm install -g grunt-cli
- curl https://gist.github.com/santiycr/5139565/raw/sauce_connect_setup.sh | bash
notifications:
  irc: "chat.freenode.net#videojs"
  hipchat:
    rooms:
      secure: MM+0xeoMvIAU7wxDIiCkQLJ6fxN9f4yftN9QqayinT62JLIusnG/5BZtRkTiYNu1QRTP8FLZNDzemmQKzDQOnTdds+lXVSHnmVz2Oq8RjRm6IYIfusAZikPgUyuXH1Kgc+P5Tn2gluuS76Vo7JKkM2/C9cqP3Wf5UtZSlYhPpsk=
    template:
    - '%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}'
addons:
  sauce_connect:
    username: sheff555
    access_key: d04372cc-0fc3-4e59-aa02-3cfd9df03240
