language: node_js
node_js:
   - "0.10"
   - "0.8"
   - "0.11"
before_script:
- npm install -g grunt-cli
- curl https://gist.github.com/santiycr/5139565/raw/sauce_connect_setup.sh | bash
notifications:
hipchat:
rooms:
secure: l5TTd5JuPAW883PtcyaIBcJI9Chr9JpsZPQAEUBKAgIEwzuS6y7t5arlkS1PwH6gi1FADzYDf+OXSIou4GkTSrIetnBcT/SAgF0gBKgIhj+eRkuCfZ4VaC7BPhfZ0hgYRE+5Ejf5BM2MJafRm0pj7OlqG4xKrQZwtuV1te5r3JY=

env:
  global:
    - secure: "Jxoh9edf1CY0dDGzVttfqOskBsv1jPMM+9PuztRJ9ZBabvFHk4YlBbP1FP6/f5Nb4GgzZzmTfNTQcpBgiaF0kQbt0gP7NysHyMOqSVLCFX2e6Q2cZ/iJL1tFldZ9Z2MtoOokrVUFYuK7iNbUtHjqlQSQerhAYyvF3Yrr79E0aGM="
    - secure: "ASb8Lnkdaxb3k34FAt8l5Uhm2dWGTScn1QXoFQzXIN2fkZVUFqhYeJarKwJeY4qI4+vaCYaccmB5VvHRjNwWcaVFun5+lYDFF3AlHZCSMUfk8Mp2chkrCN/0i6lhSwu3LLIUE+9U9G9MTYLo6hP0AXvxPQvlcj5uaHzug+GSyA4="

    addons:
  sauce_connect: true

